### ISSUE TITLE
question about config file

### ISSUE THREAD

**Issue by ZianTT** [PKU-GeekGame/gs-backend#1]
Hi, I'd like to know whether I should generate token.priv, and if so how can I generate it?

**Comment by xmcp** [comment]
It is used to sign tokens for problems (same as hackergame).

- `openssl ecparam -name secp256k1 -genkey -noout -out token.priv`
- `openssl req -x509 -key token.priv -out token.pub -days 365`

Ref: https://github.com/USTC-Hackergame/hackergame-challenge-docker#%E9%85%8D%E7%BD%AE%E8%AF%81%E4%B9%A6
