### ISSUE TITLE
Do we need to keep updated?

### ISSUE THREAD

**Issue by MALossov** [PKU-GeekGame/gs-backend#3]
## Issue Description:

Hello there! We are also students who are working on building a recruiting platform for our studio currently and are excited to see this wonderful project. 

Last month, we deployed the guiding-star project on our own server for recruitment and made modifications based on the original version in July 2023. 

We would like to inquire about the upcoming development cycle and any related update requirements.

### Development Cycle:
Could you please provide an estimate of how long the new development cycle is expected to last? Do you have a clear plan and timeline in place? If you ended your work, we shall keep updated on this.

### Update Necessity:
In the previous deployment, we made modifications based on the original version. Are there any significant security fixes required after the new development cycle? Do we need to make any additional changes to our code to ensure system security?

### Additional Information:
Based on the modifications we made to the previous version, we believe your previous version was already exceptional and outstanding. Thank you for your hard work and continuous working on this project.

**Comment by xmcp** [comment]
Thanks for your interest in this platform!

> Development Cycle

The main purpose of Guiding Star is to host [PKU GeekGame CTF](https://geekgame.pku.edu.cn/), which takes place in October~December annually. In each year we adjust this platform based on participant feedbacks and our new needs. Now adjustments from participant feedbacks are all finished (mostly user experience improvements), but there may be new adjustments according to the need of our CTF.

> Update Necessity

Recent commits updated some third-party libraries (backend: sanic 21.12 → 22.12, sqlalchemy 1.4 → 2.0; frontend: react 17 → 18, antd 4 → 5, webpack 4 → 5). If you want to modernize your codebase, you can cherry pick these updates. There are no security-related changes.

Let me know if you have other questions :)

**Comment by xmcp** [comment]
@MALossov
Also btw can you post an URL to your platform website / related advertising materials if it is public accessible? Maybe some time in the future I can use it to showcase the customizability of Guiding Star :)

**Comment by MALossov** [comment]
> @MALossov Also btw can you post an URL to your platform website / related advertising materials if it is public accessible? Maybe some time in the future I can use it to showcase the customizability of Guiding Star :)

Thanks a lot for your interest! If you need the URL, I can send it to your private mail (I can be found on [MALOSSOV](mailto://malossov@163.com)), the reason for not paste the URL here for now is that our site is still in beta (although domains are allowed to access it), and it's not done well enough. Please be assured that the Guiding Star open source license and the original `Project Guiding Star by PKUGGG Team` text at the bottom of the page have been preserved.We also have great enthusiasm in being able to contribute upstream.

We just haven't made any major changes to Guiding Star, the only bit difference is: a new email verification portal has been added (mainly due to the fact that it was difficult to apply for OAuth at our school, and we didn't get the API or license), however, the encryption and decryption algorithms currently used as the backend checksum are not very reasonable (AES is currently used), and there is still some "works but not well enough" code. I'll be in touch if I need any help.

So after all the code optimizations are done and new updates are merged, I'll consider open-sourcing it as a showcase for some of the project's customizations.

**Comment by MALossov** [comment]
> @MALossov Also btw can you post an URL to your platform website / related advertising materials if it is public accessible? Maybe some time in the future I can use it to showcase the customizability of Guiding Star :)

Now it is [御林安全招新平台](http://recruit.yulinsec.cn)

We have made some preliminary changes and are currently using it as a recruitment platform.We are extremely excited and grateful to provide you with such a wonderful platform.
