### ISSUE TITLE
[Enhancement] 增加API支持

### ISSUE THREAD

**Issue by ZianTT** [PKU-GeekGame/gs-backend#4]
既然大佬开始开发了，希望支持一下在外部直接调用API或开放Python的外部调用接口喵

**Comment by xmcp** [comment]
想加API的话直接在 src/api/endpoint/wish.py 里面增加呗？

**Comment by ZianTT** [comment]
> 想加API的话直接在 src/api/endpoint/wish.py 里面增加呗？

~~不是，指的是Admin的API，比如调用用户信息啥的~~

（仔细想想好像也不是不行，我试着实现一下
